### ISSUE TITLE
tskit error when doing two pop inference on new drosophila sims

### ISSUE THREAD

**Issue by ckyriazis** [popsim-consortium/analysis#56]
I'm having issues reading in the tree sequences from the new Drosophila Li & Stephan simulations that @jradrion just completed. I'm trying to do inference on chr2L but its hanging when the tree sequences are loaded (`ts = tskit.load(path)`) on line 39 in `smc.py` with the following error: 

`Bad edge interval where right <= left`

I can see on the [msprime docs](https://msprime.readthedocs.io/en/stable/tutorial.html) that this might be an issue when there are large fluctuations in recombination rate, which might now be present when looking at a full drosophila chromosome instead of the 3 Mb we were using before. 

Any thoughts on what to do here @jeromekelleher? @andrewkern did you run into this issue with the n_t pipeline?

**Comment by andrewkern** [comment]
I have not tried on the n_t pipeline as I'm using the other fly model there

**Comment by ckyriazis** [comment]
but you did whole genome drosophila sims right? or is the issue maybe that the effective recombination rate here is higher because of larger Ne?

**Comment by andrewkern** [comment]
yep i did whole genome sims

**Comment by jeromekelleher** [comment]
What's happened here is that the recombination distances are so fine they have gone below 32 bit resolution and the left and right coordinates of an edge are mapping back to the same physical coordinates. Not sure there's much we can do here.

This is a bug in msprime, as it should have raised an error on output telling us this had happened.
 
Can you try a different chromosome please @ckyriazis?

**Comment by andrewkern** [comment]
wow that's interesting-- is this a known bug in msprime?

**Comment by ckyriazis** [comment]
thanks @jeromekelleher  - ill give one of the other chromosomes a try and let you know.

**Comment by ckyriazis** [comment]
so i've tried all of the chromosomes and unfortunately got the same error each time. we may have to just stick with the 3 Mb sims for now unless anyone has any other ideas.

**Comment by jeromekelleher** [comment]
> wow that's interesting-- is this a known bug in msprime?

It is now! I don't think anyone has tried to do simulations this big before, so this is a pretty extreme case. We'll need to follow up on it over there.

> so i've tried all of the chromosomes and unfortunately got the same error each time. we may have to just stick with the 3 Mb sims for now unless anyone has any other ideas.

Yes, we'll have to settle for that @ckyriazis, not much we can do about the big sims now.

**Comment by jeromekelleher** [comment]
I created a bug report for this over in msprime. Sorry for all the wasted time trying to run these simulations @jradrion!
