### ISSUE TITLE
n_t DroMel African3Epoch_1S16 analysis failure

### ISSUE THREAD

**Issue by jradrion** [popsim-consortium/analysis#57]
I ran `rule all` after pulling the most recent changes to `/analysis/` and `/stdpopsim/`, and the pipeline errored out (no error message, of course) sometime after `rule simulation`. I'm going to try to debug this, but it might be worth rerunning some of the other models to make sure the pipeline still runs without error.

**Comment by jeromekelleher** [comment]
Is this based on the released 0.1.0 version?

**Comment by jradrion** [comment]
I don't know, how would I be able to tell? It's based on a pull from upstream master at around ~23:00 UTC, yesterday.

**Comment by andrewkern** [comment]
i'll look in to this too

**Comment by jradrion** [comment]
> Is this based on the released 0.1.0 version?

didn't see that you just released this, awesome! The .trees were created and look normal, so it's almost certainly going to be something on the analysis side. I'll track it down.

**Comment by jeromekelleher** [comment]
> didn't see that you just released this, awesome! The .trees were created and look normal, so it's almost certainly going to be something on the analysis side. I'll track it down.

Cool --- we should change the bit where we're pulling from GitHub to making it install from pypi,

```
$ python3 -m pip install stdpopsim==0.1.0
```
for reproducibility.

**Comment by andrewkern** [comment]
so I just ran the `HomSap` `Africa_1T12` model without problem

**Comment by jradrion** [comment]
Can you try running `DroMel` `African3Epoch_1S16`. I'm still having problems with dependencies after my update to 3.7.

**Comment by jradrion** [comment]
> @andrewkern Can you try running DroMel African3Epoch_1S16. I'm still having problems with dependencies after my update to 3.7.

I have this running now using a python 3.6 install on the `analysis` side and `stdpopsim` installed via `python -m pip install stdpopsim==0.1.0`. It's looking good so far! I'm going to close this now, and I'll open a new issue if something else pops up.
