### ISSUE TITLE
losing SNPs in Arabidopsis

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/analysis#59]
don't think there is much to be done here, but in going from a tree sequence to a vcf for Arabidopsis I'm losing ~ 1% of SNPs do to collisions between site positions with the default behavior of `tskit.write_vcf()`. Should I change the `position_transform` option of `tskit.write_vcf()`? @jeromekelleher @petrelharp

**Comment by jeromekelleher** [comment]
Depends on what you want @andrewkern. If you want to get rid of the collisions in a naive way you can use ``position_transform="legacy"``

**Comment by andrewkern** [comment]
seems to me like losing 1% of the SNPs doesn't warrant a rerun for the paper. that okay by you?

**Comment by jeromekelleher** [comment]
Totally - makes no difference.
